name: learn_flutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  url_launcher: 3.0.0
  intl: 0.15.5
  connectivity: 0.3.0
  video_player: 0.4.1
  device_info: 0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/shrine/products/backpack.png
      - assets/shrine/products/beachball.png
      - assets/shrine/products/binoculars.png
      - assets/shrine/products/brush.png
      - assets/shrine/products/chair.png
      - assets/shrine/products/chucks.png
      - assets/shrine/products/clock.png
      - assets/shrine/products/fish_bowl.png
      - assets/shrine/products/flippers.png
      - assets/shrine/products/green-shoes.png
      - assets/shrine/products/heels.png
      - assets/shrine/products/helmet.png
      - assets/shrine/products/lawn_chair.png
      - assets/shrine/products/lipstick.png
      - assets/shrine/products/popsicle.png
      - assets/shrine/products/radio.png
      - assets/shrine/products/sunnies.png
      - assets/shrine/products/surfboard.png
      - assets/shrine/products/teapot.png
      - assets/shrine/vendors/16c477b.jpg
      - assets/shrine/vendors/ali-connors.png
      - assets/shrine/vendors/peter-carlsson.png
      - assets/shrine/vendors/sandra-adams.jpg
      - assets/shrine/vendors/zach.jpg
  fonts:
      - family: AbrilFatface
        fonts:
          - asset: assets/shrine/fonts/abrilfatface/AbrilFatface-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
