name: learn_flutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  url_launcher: 3.0.0
  intl: 0.15.5
  connectivity: 0.3.0
  video_player: 0.4.1
  device_info: 0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/videos/butterfly.mp4
      - assets/animated_flutter_stickers.webp
      - assets/animated_flutter_lgtm.gif
      - assets/animated_flutter_lgtm.gif
      - assets/animated_flutter_stickers.webp
      - assets/appbar_background.jpg
      - assets/appbar/appbar_background_layer0.png
      - assets/appbar/appbar_background_layer1.png
      - assets/appbar/appbar_background_layer2.png
      - assets/appbar/appbar_background_layer3.png
      - assets/appbar/appbar_background_layer4.png
      - assets/appbar/appbar_background_layer5.png
      - assets/pesto/avatar.jpg
      - assets/pesto/image10.jpg
      - assets/pesto/image11.jpg
      - assets/pesto/image12.jpg
      - assets/pesto/image13.jpg
      - assets/pesto/image1.jpg
      - assets/pesto/image2.jpg
      - assets/pesto/image3.jpg
      - assets/pesto/image4.jpg
      - assets/pesto/image5.jpg
      - assets/pesto/image6.jpg
      - assets/pesto/image7.jpg
      - assets/pesto/image8.jpg
      - assets/pesto/image9.jpg
      - assets/pesto/logo_small.png
      - assets/pesto/logo_medium.png
      - assets/pesto/fish.png
      - assets/pesto/healthy.png
      - assets/pesto/main.png
      - assets/pesto/meat.png
      - assets/pesto/quick.png
      - assets/pesto/spicy.png
      - assets/pesto/veggie.png
      - assets/about_logo.png
      - assets/ali_connors.jpg
      - assets/drawer_logo.png
      - assets/kangaroo_valley_safari.jpg
      - assets/top_10_australian_beaches.jpg
      - assets/landscape_0.jpg
      - assets/landscape_1.jpg
      - assets/landscape_2.jpg
      - assets/landscape_3.jpg
      - assets/landscape_4.jpg
      - assets/landscape_5.jpg
      - assets/landscape_6.jpg
      - assets/landscape_7.jpg
      - assets/landscape_8.jpg
      - assets/landscape_9.jpg
      - assets/landscape_10.jpg
      - assets/landscape_11.jpg
      - assets/shrine/products/backpack.png
      - assets/shrine/products/beachball.png
      - assets/shrine/products/binoculars.png
      - assets/shrine/products/brush.png
      - assets/shrine/products/chair.png
      - assets/shrine/products/chucks.png
      - assets/shrine/products/clock.png
      - assets/shrine/products/fish_bowl.png
      - assets/shrine/products/flippers.png
      - assets/shrine/products/green-shoes.png
      - assets/shrine/products/heels.png
      - assets/shrine/products/helmet.png
      - assets/shrine/products/lawn_chair.png
      - assets/shrine/products/lipstick.png
      - assets/shrine/products/popsicle.png
      - assets/shrine/products/radio.png
      - assets/shrine/products/sunnies.png
      - assets/shrine/products/surfboard.png
      - assets/shrine/products/teapot.png
      - assets/shrine/vendors/16c477b.jpg
      - assets/shrine/vendors/ali-connors.png
      - assets/shrine/vendors/peter-carlsson.png
      - assets/shrine/vendors/sandra-adams.jpg
      - assets/shrine/vendors/zach.jpg
      - assets/cupertino_navigation/person1.jpg
      - assets/cupertino_navigation/person2.jpg
      - assets/gallery/app.dart
      - assets/gallery/demo.dart
      - assets/gallery/drawer.dart
      - assets/gallery/example_code_parser.dart
      - assets/gallery/home.dart
      - assets/gallery/item.dart
      - assets/gallery/syntax_highlighter.dart
      - assets/gallery/theme.dart
      - assets/gallery/updates.dart
  fonts:
      - family: Raleway
        fonts:
          - asset: assets/pesto/fonts/Raleway-Regular.ttf
          - asset: assets/pesto/fonts/Raleway-Medium.ttf
            weight: 500
          - asset: assets/pesto/fonts/Raleway-SemiBold.ttf
            weight: 600
      - family: AbrilFatface
        fonts:
          - asset: assets/shrine/fonts/abrilfatface/AbrilFatface-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
